ROLE_PREFIXES: frozenset[str] = frozenset(
    {
        "abuse",
        "admin",
        "billing",
        "careers",
        "compliance",
        "contact",
        "customerservice",
        "dev",
        "devnull",
        "engineering",
        "enquiries",
        "feedback",
        "general",
        "hello",
        "help",
        "helpdesk",
        "hostmaster",
        "hr",
        "info",
        "inquiries",
        "it",
        "jobs",
        "legal",
        "mailer-daemon",
        "marketing",
        "media",
        "no-reply",
        "noc",
        "noreply",
        "office",
        "operations",
        "ops",
        "postmaster",
        "press",
        "reception",
        "recruitment",
        "remove",
        "sales",
        "security",
        "service",
        "subscribe",
        "support",
        "sysadmin",
        "team",
        "tech",
        "unsubscribe",
        "usenet",
        "uucp",
        "webmaster",
        "www",
    }
)


def is_role_based(email: str) -> bool:
    """Check if the email uses a role-based prefix (info@, admin@, etc.)."""
    local = email.split("@")[0].lower()
    return local in ROLE_PREFIXES
